GetSit/Models/HallRequest.cs
using GetSit.Data.Base;
using GetSit.Data.enums;
using GetSit.Models;

namespace GetSit.Models
{
    public class HallRequest:IEntityBase
    {
        public int Id { get; set; }
        public String? comment { get; set; }
        public DateTime Date { get; set; }
        
        public ReqestStatus Status { get; set; }

        public int HallId { get; set; }
        public SpaceHall Hall { get; set; }
    }
}

GetSit/Models/SystemAdmin.cs
using GetSit.Data.Base;
using GetSit.Data.enums;
using GetSit.Data.Security;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace GetSit.Models
{
    public class SystemAdmin:IAbstractUser,IEntityBase
    {
        [Key]
        public int Id { get; set; }
        [AllowNull, DefaultValue(false)]
        public Boolean? Registerd { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required, EmailAddress]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
        [Required, Phone]
        public string PhoneNumber { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime Birthdate { get; set; }
        [AllowNull,DataType(DataType.Url), DefaultValue("resource/site/user-profile-icon.jpg")]
        public string? ProfilePictureUrl { get; set; }
        [DataType(DataType.Url), AllowNull,DefaultValue("resource/site/Cover_PlaceHolder.png")]
        public string? CoverPrictureUrl { get; set; }

        [AllowNull]
        public string? Country { get; set; }
        [AllowNull]
        public string? City { get; set; }
        [Required]
        public SystemAdminRole AdminRole { get; set; } = SystemAdminRole.Super;
    }
}

GetSit/Controllers/SystemAdminController.cs
using GetSit.Data.Security;
using GetSit.Data.Services;
using GetSit.Data;
using Microsoft.AspNetCore.Mvc;
using GetSit.Data.enums;
using GetSit.Common;
using GetSit.Data.ViewModels;
using GetSit.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace GetSit.Controllers
{
    [Authorize(Roles ="Admin")]
    public class SystemAdminController : Controller
    {
        #region Dependacies
        readonly IUserManager _userManager;
        readonly AppDBcontext _context;
        readonly ISpaceEmployeeService _providerService;
        readonly ISpaceService _spaceSerivce;
        readonly ISpaceHallService _hallService;
        readonly IHallFacilityService _hallFacilityService;
        readonly IHallPhotoService _hallPhotoService;
        readonly ISpaceService_Service _spaceService_service;
        readonly IServicePhotoService _servicePhotoService;
        readonly IBookingService _bookingService;
        readonly IHallRequestService _hallRequestService;
        readonly ISystemAdminService _systemAdminService;
        readonly ICustomerService _customerService;
        public SystemAdminController(IUserManager userManager,
            AppDBcontext context,
            ISpaceEmployeeService spaceEmployeeService,
            ISpaceService spaceService,
            ISpaceHallService hallService,
            IHallFacilityService hallFacilityService,
            IHallPhotoService hallPhotoService,
            ISpaceService_Service spaceService_service,
            IServicePhotoService servicePhotoService,
            IBookingService bookingService,
            IHallRequestService HallRequestService,
            ISystemAdminService systemAdminService,
            ICustomerService customerService)

        {
            _userManager = userManager;
            _context = context;
            _providerService = spaceEmployeeService;
            _spaceSerivce = spaceService;
            _hallService = hallService;
            _hallFacilityService = hallFacilityService;
            _hallPhotoService = hallPhotoService;
            _spaceService_service = spaceService_service;
            _servicePhotoService = servicePhotoService;
            _bookingService = bookingService;
            _hallRequestService = HallRequestService;
            _systemAdminService = systemAdminService;
            _customerService = customerService;
        }
        bool PresirvedEmail(string email)
        {
            return (_customerService.GetByEmail(email) != null ||
                    _providerService.GetByEmail(email) != null ||
                    _systemAdminService.GetByEmail(email) != null
                    );
        }
        #endregion          
        [HttpGet]
        public async Task<IActionResult> Index() 
        {
            #region Security
            var userId = _userManager.GetCurrentUserId(HttpContext);
            var user =await _providerService.GetByIdAsync(userId);
            #endregion
            List<Tuple<Space, SpaceEmployee>> Spaces = new List<Tuple<Space, SpaceEmployee>>();
            var DbSpaces = await _spaceSerivce.GetAllAsync();
			foreach (var space in DbSpaces)
			{
                if (space.IsApproved == false)
                {
                    var providers = _providerService.GetBySpaceId(space.Id);
					Spaces.Add(Tuple.Create(space, providers.FirstOrDefault()));

				}

			}
			var halls = _context.HallRequest.Where(i => i.Status == ReqestStatus.pending )
                .Include(r=>r.Hall)
                    .ThenInclude(h=>h.HallPhotos)
                /*.Include(r=>r.Hall)
                    .ThenInclude(h=>h.Space)*/
                .ToList();
            List<Tuple<HallRequest, Space>> requests = new List<Tuple<HallRequest, Space>>();
            foreach (var hall in halls)
            {
                var currentHall = _context.SpaceHall.Where(i=>i.Id == hall.HallId).FirstOrDefault();
                var space = _context.Space.Where(i => i.Id == currentHall.SpaceId).FirstOrDefault();
                requests.Add(Tuple.Create(hall, space));
            }
            var viewModel = new SystemAdminVM
            {
                hallRequest = requests,
                Spaces = Spaces,
                NumberOfCustomers = _context.Customer.Count(),
                NumberOfSpaces = _context.Space.Count(),
                NumberOfGuestBookings = _context.GuestBooking.Count(),
				NumberOfBookings = _context.Booking.Count(),
		};

            return View(viewModel);
        }
        public IActionResult SpaceRequestDetails (int spaceId)
        {
            var space = _context.Space.Where(i=>i.Id==spaceId).FirstOrDefault();
			var provider = _context.SpaceEmployee.Where(i => i.SpaceId == space.Id).FirstOrDefault();
            var viewModel = new ReviewSpaceVM
            {
                SpaceId = space.Id,
                Space = space,
                spaceEmployee = provider,
            };
			return View(viewModel);
        }
		[HttpGet]
		public async Task<IActionResult> AcceptSpaceAsync(int SpaceId)
		{
            var space = await _spaceSerivce.GetByIdAsync(SpaceId, s => s.Employees);
			space.IsApproved=true;
            var JwtSecurtiyToken = JwtTokenHelper.GenerateJwtToken(space.Employees.First().Email, space.Employees.First().Id);
            var Token = new Token
            {
                token = JwtSecurtiyToken
            };
            await _context.Token.AddAsync(Token);
            _context.SaveChanges();
            var UId = Token.Id;
			await _spaceSerivce.UpdateAsync(space.Id,space); 
            string oneTimeAddStaffLink = Url.Action("RegisterProvider", "Account", new { UID = UId, Role = (int)UserRole.Provider, token = Token.token }, Request.Scheme);
            EmailHelper.SendEmailAddStaff(space.Employees.First().Email, oneTimeAddStaffLink, space.Name);

            return RedirectToAction("Index");
		}
		[HttpPost]
		public async Task<IActionResult> RejectSpace(RejectSpaceVM vm)
		{
            var space = await _spaceSerivce.GetByIdAsync(vm.SpaceId,s=>s.Employees);
            var spaceName = space.Name;
            var ManagerEmail = space.Employees.First().Email;
            var employeeIdsToDelete = space.Employees.Select(emp => emp.Id).ToList();

            foreach (var empId in employeeIdsToDelete)
            {
                await _providerService.DeleteAsync(empId);
            }
            await _spaceSerivce.DeleteAsync(space.Id);
            EmailHelper.SendSpaceRejection(ManagerEmail,vm.Messege,spaceName);
            
            return RedirectToAction("Index");
		}
		public async Task <IActionResult> HallRequest(int requestId)
        {
			var request =await _hallRequestService.GetByIdAsync(requestId);
			var hall =await _hallService.GetByIdAsync(request.HallId,h=>h.HallPhotos);
            var currentHall = _context.SpaceHall.Where(i=>i.Id == hall.Id).FirstOrDefault();
            var space = _context.Space.Where(i => i.Id == currentHall.SpaceId).FirstOrDefault();
			var provider = _context.SpaceEmployee.Where(i => i.SpaceId == space.Id).FirstOrDefault();
            var viewModel = new ReviewSpaceVM()
            {
                Space = space,
                spaceEmployee = provider,
                hallRequest = request,
                Hall = hall,
                RequestId=request.Id,
            };
			return View(viewModel);
        }
        [HttpGet]
        public async Task<IActionResult> AcceptHallReqestAsync(int requestId)
        {
            var request = await _hallRequestService.GetByIdAsync(requestId,r=>r.Hall);
            var hall = request.Hall;
            hall.Status = HallStatus.Accepted;
            await _hallService.UpdateAsync(hall.Id,hall);
            await _hallRequestService.DeleteAsync(request.Id);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> RejectHallRequestAsync(RejectHallVM vm)
        {
            var request = await _hallRequestService.GetByIdAsync(vm.RequestId,r=>r.Hall);
            request.Hall = await _hallService.GetByIdAsync(request.HallId, h => h.Space);
            var space = await _spaceSerivce.GetByIdAsync(request.Hall.SpaceId, s => s.Employees);
            request.comment = vm.Messege;
            request.Status = ReqestStatus.Rejected;
            request.Date = DateTime.Now;
            await _hallRequestService.UpdateAsync(request.Id,request);
            EmailHelper.SendHallRejection(space.Employees.First().Email, request.comment, space.Name);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> AddAdmin()
        {

            var UserId = _userManager.GetCurrentUserId(HttpContext);
            var User = await _systemAdminService.GetByIdAsync(UserId);
            //var Space = await _spaceSerivce.GetByIdAsync((int)User.SpaceId, s => s.Photos);
            return View(new SystemAdmin()
            {
                ProfilePictureUrl = User.ProfilePictureUrl,
            });
        }
        [HttpPost]
        public async Task<IActionResult> AddAdmin(SystemAdmin NewAdmin)
        {
            
            ModelState.Remove("Password");
            if (!ModelState.IsValid)
            {
                return View(NewAdmin);
            }
            if (PresirvedEmail(NewAdmin.Email))
            {
                ModelState.AddModelError("Email", "This email already has an account.");
                return View(NewAdmin);
            }

            string password = RandomPassword.GenerateRandomPassword(8);
            // Using SpaceId as default value here
            var AddNewAdmin = new SystemAdmin()
            {
                FirstName = NewAdmin.FirstName,
                Birthdate = NewAdmin.Birthdate,
                LastName = NewAdmin.LastName,
                Email = NewAdmin.Email,
                Password = password,

GetSit/Views/SystemAdmin/HallRequest.cshtml
@using GetSit.Data.ViewModels
@using GetSit.Data.enums
@model ReviewSpaceVM

    <link href="@Url.Content("~/css/SystemAdmin.css")" rel="stylesheet" type="text/css" />
    <main class="content">
                <div class="container-fluid p-0">

                    <div class="mb-3">
                        <h1 class="h3 d-inline align-middle">Request</h1>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-xl-3">
                            <div class="card mb-3">
                                <div class="card-header">
                                    <h5 class="card-title mb-0">Sender Details</h5>
                                </div>
                                <div class="card-body text-center">
                                    <img src=".@Model.spaceEmployee.ProfilePictureUrl" alt=".@Model.spaceEmployee.FirstName"
                                        class="img-fluid rounded-circle mb-2" width="128" height="128" />
                                    <h5 class="card-title mb-0">@Model.spaceEmployee.FirstName @Model.spaceEmployee.LastName</h5>
                                    <div class="text-muted mb-2">Space Staff</div>
                                </div>

                                <hr class="my-0" />

                                <div class="card-body">
                                    <h5 class="h6 card-title">About</h5>
                                    <ul class="list-unstyled mb-0">
                                        @if(Model.spaceEmployee.Country != null){

                                        <li class="mb-1"><span data-feather="home" class="feather-sm me-1"></span> Lives
                                            in <a href="#">@Model.spaceEmployee.Country @Model.spaceEmployee.City</a></li>
                                        }
                                        <li class="mb-1"><span data-feather="briefcase" class="feather-sm me-1"></span>
                                            Works at <a href="#">@Model.Space.Name</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-8 col-xl-9">
                            <!-- ----------------------- -->
                            <div class="card">
                                <div class="card-header">

                                    <!-- pfp starts -->
                                    <div class="d-flex align-items-start">
                                        <img src=".@Model.spaceEmployee.ProfilePictureUrl" class="rounded-circle me-2"
                                            alt="@Model.spaceEmployee.FirstName" width="36" height="36">
                                        <div class="flex-grow-1">
                                            <strong>@Model.spaceEmployee.FirstName @Model.spaceEmployee.LastName</strong> Sent you an add hall request <br>
                                            <small class="text-muted">@Model.hallRequest.Date.ToShortDateString()</small>
                                        </div>
                                    </div>
                                    <!-- pfp ends -->

                                </div>
                                <div class="card-body">
                                    <!-- ------ space details starts here ------ -->
                                    <!-- Name -->
                                    <div class="mb-3">
                                        <label class="form-label">Space Name</label>
                                        <div class="border text-sm text-muted p-2 mt-1 mb-3">
                                            @Model.Space.Name
                                        </div>
                                    </div>

                                    <!-- Photos -->
                                    <div class="mb-3">
                                        <label for="formFile" class="form-label">Space Photos</label>
                                        <div class="row g-0 mt-1">
                                            @foreach(var photo in Model.Hall.HallPhotos){
                                                <div class="col-6 col-md-4 col-lg-4 col-xl-3">
                                                <img src=".@photo.Url" class="img-fluid pe-2" alt="Unsplash">
                                            </div>
                                            }
                                        </div>
                                    </div>

                                    <!-- Bio -->
                                    <div class="mb-3">
                                        <label class="form-label">Bio</label>
                                        <div class="border text-sm text-muted p-2 mt-1 mb-3">
                                            @Model.Space.Bio
                                        </div>
                                    </div>

                                    <!-- Address  -->
                                    <div class="mb-3">
                                        <label class="form-label">Space Address</label>
                                        <div class="border text-sm text-muted p-2 mt-1 mb-3">
                                            @Model.Space.Country @Model.Space.City
                                        </div>
                                    </div>

                                    <br><br>
                                    <!-- space location in map -->
                                    


                                    <!-- Create Space Btn  -->

                                    <div class="mb-3 m-edit" style="display: flex;justify-content: space-between;">
                                        <!-- Accept  -->
                                <a onclick="return confirmAccept();" asp-action="AcceptHallReqest" asp-controller="SystemAdmin" asp-route-RequestId="@Model.RequestId" class="btn btn-success">Create Hall</a>

                                            <span>
                                                <a class="btn btn-danger" data-bs-toggle="collapse"
                                           href="#Rejection" role="button" aria-expanded="false"
                                           aria-controls="Rejection">
                                            Reject
                                        </a>
                                        
                                            </span>
                                    </div>

                                    <div class="collapse mt-3" id="Rejection">
                                        <div class="card card-body">
                                            <div class="mb-3">
                                                <label for="exampleFormControlInput11"
                                                       class="form-label">Message</label>

                                                <div class="d-flex align-items-start mt-1">
                                                    <a class="pe-3" href="#">
                                                        <img src=".@Model.spaceEmployee.ProfilePictureUrl" class="rounded-circle me-2"
                                                         alt="@Model.spaceEmployee.FirstName" width="36" height="36">
                                                    </a>
                                                    <form asp-action="RejectHallRequest" class="flex-grow-1">
                                                    <input hidden asp-for="@Model.RequestId"/>
                                                    <textarea rows="2" type="text" name="Messege"
                                                        class="form-control border text-sm text-muted p-2 mt-1 form-control mb-3"
                                                        id="exampleFormControlInput11"
                                                        placeholder="Enter you message"></textarea>
                                                    <!-- send message  -->
                                                <button onclick="return confirmReject();" type="submit" class="btn btn-danger mr-5">Reject with email</button>
                                                </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- ------ form ends here ------ -->
                                </div>


                            </div>
                            <!-- ----------------------- -->
                        </div>
                    </div>

                </div>
            </main>

        </div>
    </div>

    <script src="js/app.js"></script>

@section Scripts
{
    <script>
         function confirmReject() {
            return confirm('Are you sure you want to reject this hall and send your messege?');
        }
        function confirmAccept() {
            return confirm('Are you sure you want to accept this hall and add it to the system?');
        }
    </script>
}

GetSit/Views/SystemAdmin/SpaceRequestDetails.cshtml
 @using GetSit.Data.ViewModels
@using GetSit.Data.enums
@model ReviewSpaceVM

<style>
    .m-edit {
        margin-top: 4rem !important;
        display: flex;
        justify-content: space-between;
        margin-left: 2rem;
        margin-right: 2rem;
    }
</style>

<link href="@Url.Content("~/css/SystemAdmin.css")" rel="stylesheet" type="text/css" />
<div class="wrapper">
    <div class="main">
            
        <main class="content">
            <div class="container-fluid p-0">

                <div class="mb-3">
                    <h1 class="h3 d-inline align-middle">Request</h1>
                </div>
                <div class="row">
                    <div class="col-md-4 col-xl-3">
                        <div class="card mb-3">
                            <div class="card-header">
                                <h5 class="card-title mb-0">Sender Details</h5>
                            </div>
                            <div class="card-body text-center">
                                <img src=".@Model.spaceEmployee.ProfilePictureUrl" alt="@Model.spaceEmployee.FirstName"
                                    class="img-fluid rounded-circle mb-2" width="128" height="128" />
                                <h5 class="card-title mb-0">@Model.spaceEmployee.FirstName &nbsp @Model.spaceEmployee.LastName  </h5>
                            </div>

                            <hr class="my-0" />

                            <div class="card-body">
                                <h5 class="h6 card-title">About</h5>
                                <ul class="list-unstyled mb-0">
                                    <li class="mb-1"><span data-feather="home" class="feather-sm me-1"></span> Lives
                                        in <a href="#">@Model.Space.City &nbsp @Model.Space.Street</a>
                                    </li>

                                    <li class="mb-1"><span data-feather="briefcase" class="feather-sm me-1"></span>
                                        Works at <a href="#">@Model.Space.Name</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-8 col-xl-9">
                        <!-- ----------------------- -->
                        <div class="card">
                            <div class="card-header">

                                <!-- pfp starts -->
                                <div class="d-flex align-items-start">
                                    <img src=".@Model.spaceEmployee.ProfilePictureUrl" class="rounded-circle me-2"
                                        alt="@Model.spaceEmployee.FirstName" width="36" height="36">
                                    <div class="flex-grow-1">
                                        <strong>@Model.spaceEmployee.FirstName &nbsp @Model.spaceEmployee.LastName </strong> Sent you a join request <br>
                                        <small class="text-muted">@Model.Space.JoinRequestDate</small>
                                    </div>
                                </div>
                                <!-- pfp ends -->

                            </div>
                            <div class="card-body">
                                <!-- ------ space details starts here ------ -->
                                <!-- Name -->
                                <div class="mb-3">
                                    <label class="form-label" asp-for="Space.Name">Space Name</label>
                                    <div class="border text-sm text-muted p-2 mt-1 mb-3">
                                        @Model.Space.Name
                                    </div>
                                </div>

                                    
                                <!-- Bio -->
                                <div class="mb-3">
                                    <label class="form-label">Bio</label>
                                    <div class="border text-sm text-muted p-2 mt-1 mb-3">
                                        @Model.Space.Bio
                                    </div>
                                </div>

                                <!-- Address  -->
                                <div class="mb-3">
                                    <label class="form-label">Space Address</label>
                                    <div class="border text-sm text-muted p-2 mt-1 mb-3">
                                        @Model.Space.City &nbsp  @Model.Space.Street
                                    </div>
                                </div>

                                <!-- Create Space Btn  -->

                                <div class="mb-3 m-edit">
                                    <!-- Accept  -->
                                    <a onclick="return confirmAccept();" asp-action="AcceptSpace" asp-controller="SystemAdmin" asp-route-SpaceId="@Model.Space.Id" class="btn btn-success">Create Space</a>

                                    <div>
                                        <!-- Reject -->
                                        <!-- The button triggers the message -->
                                        <span>
                                            <a class="btn btn-danger" data-bs-toggle="collapse"
                                                href="#Rejection" role="button" aria-expanded="false"
                                                aria-controls="collapseExample">
                                                Reject
                                            </a>
                                        </span>
                                    </div>
                                </div>

                                <div class="collapse mt-3" id="Rejection">
                                    <div class="card card-body">
                                        <div class="mb-3">
                                            <label for="exampleFormControlInput11"
                                                class="form-label">Message</label>

                                            <div class="d-flex align-items-start mt-1">
                                                <a class="pe-3" href="#">
                                                    <img src=".@Model.spaceEmployee.ProfilePictureUrl" class="rounded-circle me-2"
                                                        alt="@Model.spaceEmployee.FirstName" width="36" height="36">
                                                </a>
                                                <form asp-action="RejectSpace" class="flex-grow-1">
                                                    <input hidden asp-for="SpaceId"/>
                                                    <textarea rows="2" type="text" name="Messege"
                                                        class="form-control border text-sm text-muted p-2 mt-1 form-control mb-3"
                                                        id="exampleFormControlInput11"
                                                        placeholder="Enter you message"></textarea>
                                                    <!-- send message  -->
                                                <button onclick="return confirmReject();" type="submit" class="btn btn-danger mr-5">Reject with email</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!-- ------ form ends here ------ -->
                            </div>


                        </div>
                        <!-- ----------------------- -->
                    </div>
                </div>

            </div>
        </main>

    </div>
</div>

@section Scripts
{
    <script>
         function confirmReject() {
            return confirm('Are you sure you want to reject this space and send your messege?');
        }
        function confirmAccept() {
            return confirm('Are you sure you want to accept this space and add it to the system?');
        }
    </script>
}