GetSit/Controllers/ExploreController.cs
using GetSit.Data;
using GetSit.Data.enums;
using GetSit.Data.Security;
using GetSit.Data.Services;
using GetSit.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace GetSit.Controllers
{
    public class ExploreController : Controller
    {

        private readonly IUserManager _userManager;
        private readonly ISpaceHallService _hallService;
        private readonly IFavoriteHallService _favoriteService;
        public ExploreController(IUserManager userManager, ISpaceHallService hallService, IFavoriteHallService favoriteService)
        {
            _userManager = userManager;
            _hallService = hallService;
            _favoriteService = favoriteService;
        }
        public async Task<IActionResult> Index(string Key)
        {
            var data = await _hallService.GetAllAsync(h => h.HallPhotos, h => h.Space, h => h.FavoriteHalls);
            if (!String.IsNullOrEmpty(Key))
            {
                data = data.Where(p => p.Space.Name.Contains(Key)|| p.Space.City.Contains(Key) || p.Space.Country.Contains(Key)|| p.Space.Street.Contains(Key));
            }
            return View(data.Where(d=>d.Status==HallStatus.Accepted));
        }
        [HttpGet]
        public async Task<IActionResult> ToggleFavouriteHallAsync(int hallId)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                int CustomerId = _userManager.GetCurrentUserId(HttpContext);
                await _favoriteService.ToggleAysnc(hallId, CustomerId);
            }
            return RedirectToAction("Index");
        }


    }
}

GetSit/Views/Explore/Index.cshtml
@model IEnumerable<SpaceHall>
﻿@using System.Security.Claims;
@using GetSit.Data.enums
@{
    ViewData["Title"] = "Explore Page";
}
<link href="./css/Explorer.css" rel="stylesheet" type="text/css" />

<div class="main">

    <!-- Filters-container starts -->
    <div class="Filters-container">
        <p class="Filters-label">
            Filter Spaces
        </p>

        <div class="edit-container">
            <div>
                <button type="button" class="btn btn-dark btn-sm btn-edit">Within 256km</button>
                <button type="button" class="btn btn-dark btn-sm btn-edit">Up to $ __ / hr</button>
                <button type="button" class="btn btn-dark btn-sm btn-edit">Capacity</button>
                <button type="button" class="btn btn-dark btn-sm btn-edit">Activities </button>
                @*<button type="button" class="btn btn-dark btn-sm btn-edit">Amenities </button>*@
            </div>
        </div>

        <p class="Clear-Filters">Clear Filters</p>
    </div>
    <!-- Filters-container ends -->
    <!-- search input  -->
    <form asp-controller="Explore" asp-action="Index">
        <p>
            <input class="search-input-edit" type="text" name="Key" placeholder="Search by city, host or space name">
        </p>
    </form>
    <p class="Spaces-near">Spaces near Qena </p>
    <br><br>
    <!-- spaces container starts -->
    <div class="flex-wrap grid-container">

        @foreach (var hall in Model)
        {
            <!-- card 1 -->
            <div class="card card-edit grid-item card-img-top">
                @if (Context.User.Identity.IsAuthenticated && Context.User.IsInRole(UserRole.Customer.ToString()))
                {
                    <div class="love-icon">
                        <a asp-controller="Explore" asp-action="ToggleFavouriteHall" asp-route-HallId="@hall.Id">
                                
                                @if(hall.FavoriteHalls.Where(h=>h.HallId==hall.Id && h.CustomerId.ToString()==Context.User.Claims.Where(c=>c.Type==ClaimTypes.NameIdentifier).FirstOrDefault().Value).FirstOrDefault() is null)
                                {
                                    <!--Add to favs-->
                                    <i class="fa-regular fa-heart color-white"></i>
                                }
                                else
                                {
                                    <!--Remove from favs-->
                                    <i class="fa-solid fa-heart color-purple"></i>
                                }
                        </a>
                    </div>
                    
                }
                <div class="hall-price color1">
                    <div>
                        @hall.CostPerHour.ToString("N2") EG / hour
                    </div>
                </div>
                <div id="@hall.Id" class="carousel slide">
                    <div class="carousel-inner">
                        
                        @for(int i=0;i<hall.HallPhotos.Count();i++)
                        {
                            if(i==0)
                            {
                                <div class="carousel-item active" >
                                    <img  src="@hall.HallPhotos[i].Url"
                                         class="slider-image" alt="...">
                                </div>
                            }
                            else
                            {
                                <div class="carousel-item">
                                    <img src="@hall.HallPhotos[i].Url"
                             class="slider-image" alt="...">
                                </div>
                            }
                        }
                      
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#@hall.Id"
                            data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#@hall.Id"
                            data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>

                <div class="card-body">
                    <p class="space-name">@hall.Space.Name</p>
                    <div class="div-space-type-loc">
                        <p class="space-type">@hall.Type | @hall.Space.City ,@hall.Space.Country ,@hall.Space.Street</p>
                    </div>
                    <div class="div-badges">
                        @*Need add facilities badges*@
                        @if (false)
                        {                          
                            <span class="badge color1">Offer Badges</span>
                        }
                        else
                        {
                            <span class="badge color2">Offer Badges</span>
                        }
                        @if (@hall.Space.IsFast)
                        {
                            <span class="badge color1">Fast Booking</span>
                        }
                        else
                        {
                            <span class="badge color2">Fast Booking</span>

                        }

                        
                    </div>
                    

                    <a asp-controller="Booking" asp-action="Index" asp-route-HallID="@hall.Id"><div class="btn btn-dark book-now-btn">Book Now</div></a>
                </div>
            </div>
        }

        

        
        <!-- spaces container ends -->

    </div>

</div>