GetSit/Models/GuestBooking.cs
using GetSit.Data.Base;
using GetSit.Data.enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GetSit.Models
{
    public class GuestBooking : IEntityBase
    {
        // guest info
        [Key]
        public int Id { get; set; }
        [Required, RegularExpression("^[\\w'\\-,.][^0-9_!¡?÷?¿/\\\\+=@#$%ˆ&*(){}|~<>;:[\\]]{2,}$"), Display(Name = "First name")]
        public string FirstName { get; set; }
        [Required, RegularExpression("^[\\w'\\-,.][^0-9_!¡?÷?¿/\\\\+=@#$%ˆ&*(){}|~<>;:[\\]]{2,}$"), Display(Name = "Last name")]
        public string LastName { get; set; }
        [Required, Phone, Display(Name = "Phone number")]
        public string PhoneNumber { get; set; }

        // booking info
        [Required, DataType(DataType.DateTime)]
        public DateTime BookingDate { get; set; }
        [Required, DataType(DataType.Date)]
        public DateTime DesiredDate { get; set; }
        [Required, DataType(DataType.Time)]
        public TimeSpan StartTime { get; set; }
        [Required]
        public TimeSpan EndTime { get; set; }
        public float TotalCost { get; set; }
        public float Paid { get; set; }
        [Required]
        public BookingStatus BookingStatus { get; set; }

        // relations
        [ForeignKey("SpaceEmployeeId")]
        public int EmployeeId { get; set; }
        [Required]
        public SpaceEmployee Employee { get; set; }

        [Required]
        public List<BookingHall> BookingHalls { get; set; }
        public Payment Payment { get; set; }

    }
}

GetSit/Controllers/GuestBookingController.cs
using GetSit.Common;
using GetSit.Data;
using GetSit.Data.enums;
using GetSit.Data.Security;
using GetSit.Data.Services;
using GetSit.Data.ViewModels;
using GetSit.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace GetSit.Controllers
{
    [Authorize(Roles = "Provider")]
    public class GuestBookingController : Controller
    {
        private readonly AppDBcontext _context;
        private readonly IUserManager _userManager;
        private readonly ISpaceEmployeeService _providerService;
        private readonly ISpaceService _spaceService;
        private readonly ISpaceHallService _hallService;
        private readonly ISpaceService_Service _serviceService;
        private readonly IBookingHall_Service _bookingHall_service;
        private readonly IBookingHallService_Service _bookingService_Serivce;
        private readonly IPaymentService _paymentSerivce;
        private readonly IPaymentDetailService _paymentDetailService;
        private readonly IBookingService _bookingService;
        public GuestBookingController(AppDBcontext context,
            IUserManager userManager,
            ISpaceEmployeeService spaceEmployeeService,
            ISpaceService spaceService,
            ISpaceHallService spaceHallService,
            ISpaceService_Service spaceService_Serivce,
            IBookingHall_Service bookingHall_Service,
            IBookingHallService_Service bookingHallService_Service,
            IPaymentService paymentService,
            IPaymentDetailService paymentDetailService)
        {
            _context = context;
            _userManager = userManager;
            _providerService = spaceEmployeeService;
            _spaceService = spaceService;
            _serviceService = spaceService_Serivce;
            _hallService = spaceHallService;
            _bookingHall_service = bookingHall_Service;
            _bookingService_Serivce = bookingHallService_Service;
            _paymentSerivce = paymentService;
            _paymentDetailService = paymentDetailService;
        }
        public static void GetHoursAndMinutes(string timeSpanString, out int hours, out int minutes)
        {
            DateTime time;
            if (DateTime.TryParseExact(timeSpanString, "hh:mm tt", CultureInfo.InvariantCulture, DateTimeStyles.None, out time))
            {
                hours = time.Hour;
                minutes = time.Minute;
            }
            else
            {
                hours = 0;
                minutes = 0;
            }
        }
        [HttpGet]
        public async Task<IActionResult> Index(int HallId, DateTime? date)
        {

            // Get the current user 
            int id = _userManager.GetCurrentUserId(HttpContext);
            var emp = await _providerService.GetByIdAsync(id);
            var hall = await _hallService.GetByIdAsync(HallId, h => h.HallFacilities, h => h.HallPhotos);
            if (HallId < 1 || hall == null)
                return NotFound();
            if (hall.SpaceId != emp.SpaceId)
                return RedirectToAction("AccessDenied", "Account");

            var space = await _spaceService.GetByIdAsync(hall.SpaceId, s => s.Services,
                s => s.Services,
                s => s.WorkingDays,
                s => s.Photos);
            space.Services = _serviceService.GetBySpaceId(hall.SpaceId, s => s.ServicePhotos);
            AvailableSlots slots = new AvailableSlots(_context);
            var filterDate = (date != null) ? (DateTime)date : DateTime.Today;
            var viewModel = new GuestBookingVM
            {
                SelectedSpace = space,
                HallId = hall.Id,
                SelectedHall = hall,
                FilterDate = filterDate,
                AvailableSlots = slots.GetAvailableSlotsForDay(hall.Id, filterDate),
                SlotsForWeek = slots.GetAvailableSlotsForWeek(hall.Id, filterDate)
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Index(GuestBookingVM viewModel)
        {
            int id = _userManager.GetCurrentUserId(HttpContext);
            var emp = await _providerService.GetByIdAsync(id);
            #region GET view model for errors

            var hall = await _hallService.GetByIdAsync(viewModel.HallId, h => h.HallFacilities, h => h.HallPhotos);
            if (viewModel.HallId < 1 || hall == null)
                return NotFound();
            if (hall.SpaceId != emp.SpaceId)
                return RedirectToAction("AccessDenied", "Account");

            var space = await _spaceService.GetByIdAsync(hall.SpaceId, s => s.Services,
                s => s.Services,
                s => s.WorkingDays,
                s => s.Photos);
            space.Services = _serviceService.GetBySpaceId(hall.SpaceId, s => s.ServicePhotos);
            AvailableSlots slots = new AvailableSlots(_context);
            var filterDate = viewModel.DesiredDate;
            var IndexModel = new GuestBookingVM
            {
                SelectedSpace = space,
                HallId = hall.Id,
                SelectedHall = hall,
                AvailableSlots = slots.GetAvailableSlotsForDay(hall.Id, filterDate),
                SlotsForWeek = slots.GetAvailableSlotsForWeek(hall.Id, filterDate),
                FilterDate = filterDate
            };



            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("DesiredDate", "Make sure you press the Check availability then choose your timing.");
                return View(IndexModel);
            }
            if (viewModel.DesiredDate.Date< DateTime.Now.Date)
            {
                ModelState.AddModelError("DesiredDate", "Choose a valid booking date.");
                return View(IndexModel);
            }
            #endregion

            int startH = 0, startM = 0; GetHoursAndMinutes(viewModel.StartTime, out startH, out startM);
            TimeSpan start = new TimeSpan(startH, startM, 0);
            int endH = 0, endM = 0; GetHoursAndMinutes(viewModel.EndTime, out endH, out endM);
            TimeSpan end = new TimeSpan(endH, endM, 0);

            if(start.Ticks < DateTime.Now.TimeOfDay.Ticks)
            {
                ModelState.AddModelError("StartTime", "Choose a valid booking time.");
                return View(IndexModel);

            }

            float NumberOfHours = (float)(end - start).TotalHours;

            if (NumberOfHours <= 0)
            {
                return View(IndexModel);
            }

            /*Send unavailable error to the employee*/
            if (!slots.IsTimeSlotAvailable(hall.Id, viewModel.DesiredDate, start, end))
            {
                return View(IndexModel);
            }

            // save the booking details into the database
            try
            {
                // Add Guest Booking
                var GuestBooking = new GuestBooking
                {
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    PhoneNumber = viewModel.PhoneNumber,
                    EmployeeId = id,
                    BookingDate = DateTime.Now,
                    DesiredDate = viewModel.DesiredDate,
                    StartTime = start,
                    EndTime = end,
                    TotalCost = 0,
                    Paid = 0,
                    BookingStatus = BookingStatus.Accepted,
                };
                await _context.GuestBooking.AddAsync(GuestBooking);
                await _context.SaveChangesAsync();

                // Add Payment
                var payment = new Payment
                {
                    Status = PaymentStatus.Pending,
                    TotalCost = 0,
                    PaidAmount = 0,
                    LastUpdate = DateTime.Now,
                    GuestBookingId = GuestBooking.Id,
                    isGuest = true
                };
                await _paymentSerivce.AddAsync(payment);

                // Add Booked hall with its paymrnt detail
                var BookingHall = new BookingHall
                {
                    NumberOfUnits = 1,
                    PricePerUnit = hall.CostPerHour,
                    HallId = hall.Id,
                    GuestBookingId = GuestBooking.Id,
                    isGuest = true
                };
                await _bookingHall_service.AddAsync(BookingHall);

                var paymentHallDetail = new PaymentDetail
                {
                    TotalCost = hall.CostPerHour * NumberOfHours,
                    Status = PaymentStatus.Pending,
                    Type = PaymentType.Cash,
                    PaymentId = payment.Id,
                    BookingHallId = BookingHall.Id,
                };
                await _paymentDetailService.AddAsync(paymentHallDetail);

                GuestBooking.TotalCost += hall.CostPerHour * NumberOfHours;

                // Add Selected Services each with its payment detail
                foreach (KeyValuePair<int, int> ServiceQuantity in viewModel.SelectedServicesQuantities)
                {
                    if (ServiceQuantity.Value == 0)
                    {
                        continue;
                    }
                    var service = await _serviceService.GetByIdAsync(ServiceQuantity.Key);
                    var BookingHallService = new BookingHallService
                    {
                        ServiceId = ServiceQuantity.Key,
                        NumberOfUnits = ServiceQuantity.Value,
                        PricePerUnit = service.Price,
                        BookingHallId = BookingHall.Id,
                    };
                    await _bookingService_Serivce.AddAsync(BookingHallService);

                    var paymentServiceDetail = new PaymentDetail
                    {

GetSit/Views/GuestBooking/Details.cshtml
@using GetSit.Data.ViewModels
@using GetSit.Data.enums
@model BookingDetailsVM

<link href="~/css/bookingDetails.css" rel="stylesheet"/>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/js/bootstrap.bundle.min.js"></script>

<div class="booking-details-container">
    <div class="col-md-7 order-box box">
        <h3>Order : #Guest_@Model.Booking.Id <span class="order-date">@Model.BookingDate.ToString("dddd, dd MMMM yyyy") at @Model.BookingDate.ToString("hh:mm tt")</span></h3>
        <hr />
        <ul class="order-list">
            <li>
                <div class="product-card booking-hall fade-in">
                    <div class="product-content">
                        <div class="product-photo">
                            <img src=".@Model.HallDetail.BookingHall.Hall.HallPhotos.First().Url" alt="Item 2 Photo">
                        </div>
                        <div class="booking-details">
                            <div>
                                <h3 class="product-name">@Model.HallDetail.BookingHall.Hall.Type</h3>
                                @{
                                    var spanStart = new DateTime(Model.StartTime.Ticks).ToString("hh:mm tt");
                                    var spanEnd = new DateTime(Model.EndTime.Ticks).ToString("hh:mm tt");
                                }
                                <p>form @spanStart to @spanEnd</p>
                            </div>
                            <div class="booking-actions">
                                @if (Model.HallDetail.Status == PaymentStatus.Paid)
                                {
                                    <div class="booking-status paid">Paid</div>
                                }
                                else if(Model.HallDetail.Status == PaymentStatus.Uncompleted)
                                {
                                    <div class="booking-status not-paid">Not Completed</div>
                                }
                                else
                                {
                                    <div class="booking-status not-paid">Not Paid</div>
                                }
                                <div class="booking-cost">$@Model.HallDetail.TotalCost.ToString("N2")</div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            @foreach(var service in Model.servicesDetails)
            {
                <li>
                    <div class="product-card booking-hall fade-in">
                        <div class="product-content">
                            <div class="product-photo">
                                <img src=".@service.BookingHallService.Service.ServicePhotos.First().Url" alt="Item 2 Photo">
                            </div>
                            <div class="booking-details">
                                <div>
                                    <h3 class="product-name">@service.BookingHallService.Service.Name</h3>
                                    <p>Quantity: @service.BookingHallService.NumberOfUnits</p>
                                </div>
                                <div class="booking-actions">
                                    @if (service.Status == PaymentStatus.Paid)
                                    {
                                        <div class="booking-status paid">Paid</div>
                                    }
                                    else if (service.Status == PaymentStatus.Uncompleted)
                                    {
                                        <div class="booking-status not-paid">Not Completed</div>
                                    }
                                    else
                                    {
                                     <div class="booking-status not-paid">Not Paid</div>
                                    }
                                    <div class="booking-cost">$@service.TotalCost.ToString("N2")</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            }
        </ul>
        <div style="display: flex;justify-content: flex-end;">
            <div>
                <div class="total-cost">
                    <div>Total : </div>
                    <p>$@Model.TotalCost.ToString("N2")</p>
                </div>
                <div class="total-cost">
                    <div>Paid : </div>
                    <p>@{
                            var paid = (float)Model.Paid;
                        }$@paid.ToString("N2")</p>
                </div>
                <hr/>
                <div class="total-cost">
                    <div>To pay : </div>
                    @{
                        float rest = Model.TotalCost - paid;
                    }
                    <p>$@rest.ToString("N2")</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 right-side">
        <div class="customer-box box">
            <h5>Customer details</h5>
            <div class="customer-card">
                <div class="customer-avatar">
                    <img src="../resources/site/user-profile-icon.jpg" alt="Customer Photo">
                </div>
                <div class="details">
                    <div class="name">@Model.FirstName @Model.LastName</div>
                    <div class="phone">Phone: @Model.PhoneNumber</div>
                </div>
            </div>
        </div>
        <div class="employee-box box">
            <h5>Employee details</h5>
            <div class="customer-card">
                <div class="customer-avatar">
                    <img src="../@Model.Employee.ProfilePictureUrl" alt="Employee Photo">
                </div>
                <div class="details">
                    <div class="name">@Model.Employee.FirstName @Model.Employee.LastName</div>
                    <div class="phone">Phone: @Model.Employee.PhoneNumber</div>
                </div>
            </div>
        </div>
    </div>
    <div class="actions">
        <a onclick="return confirmPay();" class="add-item-btn pay-btn" asp-action="Pay" asp-controller="GuestBooking" asp-route-PaymentId="@Model.Booking.Payment.Id">Accept payment</a>
        <a class="add-item-btn apply-btn" asp-action="Edit" asp-controller="GuestBooking" asp-route-bookingId="@Model.Booking.Id">Edit Booking</a>
        <a onclick="return confirmCancel();" class="add-item-btn cancel-btn" asp-action="Cancel" asp-controller="GuestBooking" asp-route-BookingId="@Model.Booking.Id">Cancel</a>
   </div>
</div>
@section scripts{
    <script>

        $(document).ready(function () {
            setupDropDownService();
        });
        
        function setupDropDownService() {
            var $dropdown = $(".service-menu");

            $dropdown.on("click", ".counter-btn", function (e) {
                e.preventDefault();
                var $counterContainer = $(this).closest(".counter-container");
                var $counterValue = $counterContainer.find(".counter-value");
                var currentValue = parseInt($counterValue.text()) || 0;
                var increment = $(this).hasClass("increment") ? 1 : -1;

                var newValue = currentValue + increment;
                if (newValue < 0) {
                    newValue = 0;
                }

                $counterValue.text(newValue);
                // Update the hidden input field with the selected quantity
                var $parent = $(this).closest(".edit-list-item");
                var serviceId = $parent.find(".service-quant").attr("index");
                $(`#SelectedServicesQuantities_${serviceId}`).val(newValue);
                updateReceipt();
                // Prevent dropdown from closing when clicking on the counter buttons
                e.stopPropagation();
            });
        }
        function confirmCancel() {
            return confirm('Are you sure you want to cancel this booking?');
        }
        function confirmPay() {
            return confirm('Are you sure you want to accept this booking payment?');
        }
    </script>
}

GetSit/Views/GuestBooking/e.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}