GetSit/Models/Space.cs
using GetSit.Data.Base;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace GetSit.Models
{
    public class Space : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Bio { get; set; }
        [Required]
        public string Country { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public DateTime JoinRequestDate { get; set; }
        [AllowNull]
        public DateTime JoinDate { get; set; }
        [Required]
        public string Street { get; set; }
        [Required]
        public string GPSLocation { get; set; }
        [Required,DefaultValue(true)]
        public bool IsFast { get; set; }
        [AllowNull]
        public string? BankAccount { get; set; }
        [Required, DefaultValue(false)]
        public bool IsApproved { get; set; }
        [AllowNull,DefaultValue("resource/site/logo-social.png")]
        public string? SpaceLogo { get; set; }
        [AllowNull, DefaultValue("resource/site/Cover_PlaceHolder.png")]
        public string? SpaceCover { get; set; }
        [AllowNull]
        public string? Email { get; set; }
        [AllowNull]
        public string? Facebook { get; set; }
        [AllowNull]
        public string? Twitter { get; set; }
        [AllowNull]
        public string? Instagram { get; set; }
        public List<SpacePhoto>? Photos  { get; set; }
        public List<SpacePhone>? Phones { get; set; }
        public List<SpaceWorkingDay>? WorkingDays { get; set; }
        public List<SpaceService>? Services { get; set; }
        public List<SpaceHall>? Halls { get; set; }
        public List<SpaceEmployee>? Employees { get; set; }
    }
}

GetSit/Controllers/SpaceController.cs
using Microsoft.AspNetCore.Mvc;
using GetSit.Data.ViewModels;
using GetSit.Data;
using GetSit.Models;

namespace GetSit.Controllers
{
    public class SpaceController : Controller
    {
        public readonly AppDBcontext _context;
        private object _webHastEnvronment;

        public SpaceController(AppDBcontext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddHall(int SpaceId = 1)
        {
            //if (SpaceId == null) { return NotFound(); }
            HallVM vm = new HallVM();
            var sp = _context.Space.Where(x => x.Id == SpaceId).FirstOrDefault();
            var hall = new SpaceHall()
            {
                Space = sp,
                SpaceId = SpaceId,
            };
            vm.Hall = hall;

            return View(vm);
        }
        [HttpPost,ActionName("AddHall")]
        public IActionResult AddHall(HallVM vm)
        {
            var temp = new List<HallPhoto>();
                foreach (var file in vm.Files)
                {
                    if (file != null && file.Length > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/resources/HallPhotos", fileName);
                        
                        using (var fileSrteam = new FileStream(filePath, FileMode.Create))
                        {
                              file.CopyToAsync(fileSrteam);
                        }
                        filePath = "./resources/HallPhotos/" + fileName;
                        var tmp = new HallPhoto()
                        {
                            Url = filePath,
                        };
                        temp.Add(tmp);
                }
                }

            vm.Hall.SpaceId = 1;
            vm.Hall.HallPhotos = temp;

            _context.SpaceHall.Add(vm.Hall);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

GetSit/Controllers/SpacesController.cs
using GetSit.Data.Services;
using Microsoft.AspNetCore.Mvc;

namespace GetSit.Controllers
{
    public class SpacesController : Controller
    {
        public readonly ISpaceService _service;
        public SpacesController(ISpaceService service)
        {
            _service = service;
        }
        public async Task<IActionResult >Index()
        {
            var data =await _service.GetAll();
            return View(data);
        }
    }
}

GetSit/Views/Space/AddHall.cshtml
@using GetSit.Data.ViewModels
@model HallVM
<h1>
    @Model.Hall.Space.Name
</h1>
<form  method="post" action="@Url.Action("AddHall", "Space")" enctype="multipart/form-data">
    
    <div class="mb-3">
        <label class="form-label">Description</label>
        <input type="text" class="form-control" asp-for="@Model.Hall.Description" placeholder="Add hall description .....">
    </div>

    <div class="mb-3">
        <label class="form-label">Capacity</label>
        <input type="text" class="form-control" asp-for="@Model.Hall.Capacity" placeholder="Enter hall Capacity...">
    </div>
    <div class="mb-3">
        <label class="form-label">Cost Per Hour</label>
        <input type="text" class="form-control" asp-for="@Model.Hall.CostPerHour" placeholder="Enter hall Cost Per Hour...">
    </div>
    <select class="form-select" aria-label="Hall type" asp-for="@Model.Hall.Type">
        <option selected>Select hall type</option>
        <option value="1">Desk</option>
        <option value="2">MeetingRoom</option>
        <option value="3">ClassRoom</option>
        <option value="4">Office</option>
    </select>
    

    <div class="mb-3">
        <label  class="form-label">Multiple files input example</label>
        <input class="form-control" type="file" asp-for="@Model.Files" multiple>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    
</form>